server:
  port: 8800

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.34.77.175:3306/imongjeomong?serverTimezone=Asia/Seoul
    username: mong
    password: mong1q2w

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

openData:
  tasu:
    serviceKey: HGWbiXI4puxU2CzKvcLxn5CesxFWEHG%2F49E1OBVZH4N3flzq0q%2B442V4Ii2Bk43fuLm0jmkitNv5Qaxxb1U6ag%3D%3D
  parkingLot:
    serviceKey: 2SCrtJa2q0nUfUhgHMRiEsqJA4sGLiXD0aih2eXhem3ETCD8GhjlZ66%2FrncMbl3A12VywlgTNLrcNWKW%2B4K4kg%3D%3D
  attraction:
    serviceKey: HGWbiXI4puxU2CzKvcLxn5CesxFWEHG%2F49E1OBVZH4N3flzq0q%2B442V4Ii2Bk43fuLm0jmkitNv5Qaxxb1U6ag%3D%3D


cloud:
  aws:
    credentials:
      access-key: AKIA2SPMQZMSZJ2JE7BE
      secret-key: 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
    s3:
      bucket: imongjeomong
    region:
      static: ap-northeast-2
    stack:
      auto: false
